### ISSUE TITLE
About　train

### ISSUE THREAD

**Issue by Easyfeng222** [naviocean/pseudo-3d-pytorch#2]
Excuse me, when I have prepared UCF101, the problem is produce. Looking forward your reply. Thanks in advance.
python main.py /home/feng/pseudo-3d-pytorch/data 
UCF101 data set
Loading P3D model
=> creating model P3D
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    main()
  File "main.py", line 48, in main
    Training(name_list=name_list, num_classes=num_classes, modality='RGB', **args)
  File "/home/feng/pseudo-3d-pytorch/train.py", line 43, in __init__
    self.train_loader, self.val_loader = self.loading_data()
  File "/home/feng/pseudo-3d-pytorch/train.py", line 206, in loading_data
    pin_memory=True)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 145, in __init__
    sampler = RandomSampler(dataset)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/sampler.py", line 61, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by naviocean** [comment]
It seems your data folder is empty or structure is wrong. Could you please share the structure of data folder?
